---
dist: trusty
language: python
python:
- '3.6'
sudo: true
cache:
    apt: true
    pip: true
addons:
  apt:
    packages:
    - gdal-bin
    - gfortran
    - libatlas-base-dev
    - libatlas-dev
    - libgdal1-dev
    - liblapack-dev
    - libproj-dev
install:
- export CPLUS_INCLUDE_PATH="/usr/include/gdal"
- export C_INCLUDE_PATH="/usr/include/gdal"
  # The python gdal bindings version need to match the gdal version of the system
- travis_retry pip install --upgrade pip cattrs
- travis_retry pip install --upgrade pytest pytest-cov coveralls GDAL==1.10.0 rasterio[s3] 'scipy<1.5.0' pandas==1.0.5
  # flake8 version should match .pre-commit-config.yaml
- travis_retry pip install flake8==3.8.2
- travis_retry pip install -e .[test]
- pip freeze
  # Either both set or none. See: https://github.com/mapbox/rasterio/issues/1494
- '[ "${AWS_SECRET_ACCESS_KEY}" ] || unset AWS_ACCESS_KEY_ID'

script:
- ./check-code.sh --runslow
after_success: coveralls

before_deploy:
- pip install s3pypi
- python setup.py sdist

deploy:
- provider: script
  script: s3pypi --bucket datacube-core-deployment
  on:
    all_branches: true  # Let the condition below decide if the branch is to be deployed
    condition: $TRAVIS_BRANCH = "develop" || ! -z "${TRAVIS_TAG}"  # develop branch or tags
    repo: GeoscienceAustralia/eo-datasets  # Don't attempt to deploy from forks
- provider: releases
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^eodatasets3-[0-9]+\\.[0-9]+"
    repo: GeoscienceAustralia/eo-datasets
  api-key:
    secure: p9mx+tyqJ2lIRXnDj39L2tcm03/qSZiH6+VyS2CeOLmxBWBqbTZMhdft3mgiVHH9U2b8ZpwxuzfQ+kXXasNVFuqRo3lCWorvqvqZ7v3bJt6tIIswcYEkvNHbIWXSt558fNRp2DaJRQRo1jzOT5685qzHr+6wsTkTxYzcK9oaqKxv+MjlvkD/hednFgSmlkLXcnO8R+iRdHQe08itvTAZILK/pEeV2U6RbF5HqkuyCatVlwWJdtztaqnycT67Ze7xmH90NU3eBkH5o5oGP3ilTdVpt1ZFl6bGC7va3RkXeBXTLL8nz8S0Tzh/FqtKc88HwALoMDF6sDPp+4MDIazgH8KvBwaCA0fz+RUrbiYwgcJqraMiYl0Pr/qpLCfR5fCxPdFNx98R6aGUmljDH5obggRPE0Q2wl0hqZM1Aq6i/ERCL9SdirnB5zAkd+nYKgYAF9vWA8Yedh01Gv21C/qeKa0yNTCfUeGxUfjla1A+K9jrPmh+Q2Hku1jL1H+wFaV3c45UDN0rvC1q4LrlGlymREH90YTJTwtW7tPbdIoWnS9EUljXIIhHohF9Hr3+bN1XXY91NVTmmUTJ+ZArXhXJi/6d+Cl5TiAN7+H/rDkrJ83KQ4MnVYoNAuIrsG1sFVm5BhkzF77TJb8kh8qK1QkWGKGzQFHK+1n5EiyPc2gqlOs=
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
        secure: lsNEGmbGTX8Dcu4ruuEchsrUjqtNisrnbE5qq7hWm0xYseav5RdokfJhXw2k++qOiKJntwqM5BrE1DQLDdhEEuViiy1Q8dyqnjIfiV41WjIPCm3qtBRvg5J+pHi6aBn0rNHRd8scCZEIX3BecLpkX61LDcX0Q0HTIe4bAccpIg7TjZk2Viln2G2oEfKkaLlXnF2SY2dUdkUrEDql+rGc1j1JGFZHwSEEZEF+dBX73wQPPHQRAhF5yL76qF2A1Ceh9v2ZT/4DcX9MEcZzHxc83zwiDL9/0UKb7cKDQk4kqqtq4E2l99HkTwdZmsjPnFvhh1Rt0dXYuwdEBkx/s9A+1ndgat7a9strOhnKZt8Bf6zWLEHab6opEZfEAn4+y2hotx3UKHeQWGCZ0GeWFQg+BUjL1gq7wGnmCjc+990nL74hk2FCKS65RXR77oY/D3jlWDIRnkC1hy7YH21C1sJH66MyyqbA1aPCOtHfGxQ5/EoIp9bN7sZHwz/VPX7YrGnf8Ams+S3hZJTL0N+YCYR2QLYw8uVZAw48zOb7tmnevpsAxlBHHTKUoYTzv8SpRdK1AhNVgIHmdk3dTsVvbs2MpjUsDKqM8rKqlb77KzQhYYVOpQIQZwDlqUT42UMW4s+wiVFgpwBFUddbKgyyh99lF2eIpW6Oi0Llc+5yCnULs8A=
